# 用物件導向的方式，建立屬於自己的normal scaler（標準化)

## sklearn：StandardScaler

In [1]:
from sklearn.preprocessing import StandardScaler

data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print(scaler.fit(data))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [2]:
print(scaler.mean_)

[0.5 0.5]


In [3]:
print(scaler.var_)

[0.25 0.25]


In [4]:
print(scaler.transform(data))

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [5]:
print(scaler.transform([[2, 2]]))

[[3. 3.]]


## 利用物件導向的方式另外建立一個StandardScaler

In [6]:
import numpy as np
import pandas as pd

In [7]:
class HappyStandardScaler:
        
    def __init__(self):
        self.mean = None
        self.std = None
        self.var = None
    
    def fit(self,data):
        self.mean = np.mean(data,axis=0)
        self.std = np.std(data,axis=0)
        self.var = np.var(data,axis=0)
        
    def transform(self,data):
        standard_data = (np.array(data)-self.mean)/self.std
        return standard_data
    
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)

In [8]:
inputData = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [9]:
happyScaler = HappyStandardScaler()
happyScaler.fit(inputData)

In [10]:
happyScaler.mean

array([0.5, 0.5])

In [11]:
happyScaler.std

array([0.5, 0.5])

In [12]:
happyScaler.var

array([0.25, 0.25])

In [13]:
happyScaler.transform(inputData)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [16]:
happyScaler.transform([[2,2]])

array([[3., 3.]])

## fit_transform

In [17]:
new_happyScaler = HappyStandardScaler()

In [18]:
new_happyScaler.fit_transform(inputData)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])